# Site settings
title: Linsey Raymaekers
# email: @example.com

description: > # this means to ignore newlines until "baseurl:"
  iLinsey Raymaekers studied Human-Computer Interaction at the University of Hasselt, Belgium. She started making video games through game jams and One Game A Month, and spent a year visiting game events across Europe while she completed her degree. After years of writing poetry and playing music as emotional outlets and forms of self-expression, she is now interested in how game development can be pursued for similar reasons and motivations. She is currently an intern in game programming at Honig Studios in Berlin.

baseurl:  # the subpath of your site, e.g. /blog/

url:  # the base hostname & protocol for your site

twitter_username: linsey_ray
github_username:  linseyray

# Build settings
markdown: kramdown

highlighter: pygments


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

